# for development
version: '3.4'
services:
  mysql:
    container_name: project_d_api_mysql
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password --init-file=/data/mysql-init.sql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init.sql:/data/mysql-init.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
  adminer:
    depends_on:
      - mysql
    links:
      - mysql:db
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mongodb:
    container_name: project_d_api_mongodb
    image: mongo:4.0.6
    ports:
      - "27017"
  redis:
    container_name: project_d_api_redis
    image: redis:latest
    ports:
      - "6379"
  nodejs:
    container_name: project_d_api_nodejs
    depends_on:
      - mongodb
      - mysql
      - redis
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - port=3000
    ports:
      - "3000"
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
      - ./babel.config.js:/app/babel.config.js
      - ./.flowconfig:/app/.flowconfig
      - ./package.json:/app/package.json
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/projectD
      - MYSQL_URI=mysql://root:mysql@mysql:3306/project_d
      - FACEBOOK_APP_ID=302560177128212
      - FACEBOOK_APP_SECRET=2027ad595a6f3cea53e3ea3cd357a546
    command:
      - dev
  nginx:
    container_name: project_d_api_nginx
    depends_on:
      - nodejs
    image: nginx
    ports:
      - "80"
      - "443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - PORT=3000
    command: /bin/bash -c "envsubst '$$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
